README: better explain relationship of repo/list
MPEGGroup/OpenFontFormat pull request #5
Opened 2020-08-27 04:11 UTC by davelab6

Please don't merge yet, will edit after there's more clarity on this

2020-09-23 01:04 UTC, stuaxo commented
In my last contract we used "WIP" in the ticket description to say "don't merge this" having a "work in progress" label could work here.

2020-09-23 06:39 UTC, alerque commented
@stuaxo Draft PR's are a relatively new tool in the GitHub toolbox. There is no need for WIP titles, descriptions, or labels. Draft PR's don't have a merge button and they cannot be merged until somebody with the right powers (the same powers that could edit the title or change the labels) marks them as ready for review.

2020-09-23 08:06 UTC, stuaxo commented
Fantastic :) tbh I'm having trouble keeping up with all the new things being added to github.

2020-09-23 13:02 UTC, davelab6 commented
@vlevantovsky I'm sure I got some details wrong but I'd be grateful if you could take a look :)

2020-09-23 13:03 UTC, davelab6 commented
I've enabled edits by maintainers so you can correct the file on my fork's branch directly.

2020-09-23 13:25 UTC, stuaxo commented on README.md
> +(Sadly file attachments are not available in the archive, but you can request copies be reposted older members, or search the MPEG filestore and ISO FileFlex document repositories.)
Should this be -

> reposted **by** older members

?

2020-09-23 13:29 UTC, alerque approved these changes

2020-09-23 20:27 UTC, alerque requested changes

2020-09-23 20:27 UTC, alerque commented on README.md
> +(Sadly file attachments are not available in the archive, but all formal input and output documents can be found in MPEG document registry and on ISO Livelink document repositories (please note that
```suggestion
(Sadly file attachments are not available in the archive, but all formal input and output documents can be found in MPEG document registry and on ISO Livelink document repositories (please note that the access to those document archives is password protected and available only to active members of SC29.))
```

2020-09-23 21:29 UTC, stuaxo commented on README.md
> +(Sadly file attachments are not available in the archive, but all formal input and output documents can be found in MPEG document registry and on ISO Livelink document repositories (please note that
in *the* MPEG document registry

2020-09-23 22:49 UTC, davelab6 commented
Thanks for the corrections Vlad! I'd like to take one more pass on this before you merge, by EOW.

2020-09-24 04:31 UTC, davelab6 commented
Note to self, John Hudson posted some stuff on the list relevant to this that I want to pull in

2020-09-24 10:53 UTC, simoncozens commented
This is brilliant, and adds a lot more clarity to expectations around how changes to the standard (ought to) happen.

2020-09-29 22:38 UTC, alerque approved these changes

2020-10-02 01:39 UTC, davelab6 commented
@vlevantovsky would you like any more changes before merging this? In happy to see it go up and I'll follow up with a second PR with other details later? :)

2020-10-02 02:29 UTC, vlevantovsky commented
> If no objections were raised, or if all objections were retraced, ...

Did you really mean to say "retraced", or "retracted"?

2020-10-02 04:01 UTC, davelab6 commented
Typo

2020-10-02 04:43 UTC, vlevantovsky approved these changes

2020-10-02 04:44 UTC, merged